### ISSUE TITLE
Thanos-compact does not automatically disable compaction for blocks with large index.

### ISSUE THREAD

**Issue by rbounds** [thanos-io/thanos#3750]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.17.2 (branch: HEAD, revision: 37e6ef61566c7c70793ba6d128f00c4c66cb2402)
  build user:       circleci@2c49ee4f4029
  build date:       20201208-10:11:27
  go version:       go1.15
  platform:         linux/amd64

**Object Storage Provider**:
GCS

**What happened**:
- thanos-compact halts when index size exceeds 64GiB
- thanos-compact seems to continue to halt after marking the blocks as `no-compact` manually

**What you expected to happen**:
- Compactor automatically disables compaction for this block and continues.
- Manually marking a block as `no-compact` allows thanos-compact to run with out halt.

**Full logs to relevant components**:

```
"level=error ts=2021-01-20T05:13:29.348393505Z caller=compact.go:423 msg=\"critical error detected; halting\" err=\"compaction: group 0@7637943154331160108: compact blocks [/var/thanos/compact/compact/0@7637943154331160108/01EBG9FRFSSD8ZEWXBD34NY0XX /var/thanos/compact/compact/0@7637943154331160108/01EBNG1HPA6D0P22KY3ZH89TBY]: \\\"/var/thanos/compact/compact/0@7637943154331160108/01EWEE6FM9YDMQW1RV3MWKMGM2.tmp-for-creation/index\\\" exceeding max size of 64GiB\"\n"
"level=error ts=2021-01-22T00:54:09.703347565Z caller=compact.go:423 msg=\"critical error detected; halting\" err=\"compaction: group 0@7637943154331160108: compact blocks [/var/thanos/compact/compact/0@7637943154331160108/01EBG9FRFSSD8ZEWXBD34NY0XX /var/thanos/compact/compact/0@7637943154331160108/01EBNG1HPA6D0P22KY3ZH89TBY]: \\\"/var/thanos/compact/compact/0@7637943154331160108/01EWK216B7XAZTVQNJ4S5E7GGD.tmp-for-creation/index\\\" exceeding max size of 64GiB\"\n"
"level=error ts=2021-01-23T05:15:31.944994835Z caller=compact.go:423 msg=\"critical error detected; halting\" err=\"compaction: group 0@7637943154331160108: compact blocks [/var/thanos/compact/compact/0@7637943154331160108/01EBG9FRFSSD8ZEWXBD34NY0XX /var/thanos/compact/compact/0@7637943154331160108/01EBNG1HPA6D0P22KY3ZH89TBY]: \\\"/var/thanos/compact/compact/0@7637943154331160108/01EWP4NZG0GG172MVPWVR7XFBG.tmp-for-creation/index\\\" exceeding max size of 64GiB\"\n"
"level=error ts=2021-01-26T04:10:35.300971918Z caller=compact.go:423 msg=\"critical error detected; halting\" err=\"compaction: group 0@7637943154331160108: compact blocks [/var/thanos/compact/compact/0@7637943154331160108/01EBG9FRFSSD8ZEWXBD34NY0XX /var/thanos/compact/compact/0@7637943154331160108/01EBNG1HPA6D0P22KY3ZH89TBY]: \\\"/var/thanos/compact/compact/0@7637943154331160108/01EWXKAAEQ4M0HK0T92GKCAQXN.tmp-for-creation/index\\\" exceeding max size of 64GiB\"\n"
```

**Anything else we need to know**:
These blocks where marked with `no-compact-mark.json` via `thanos tools bucket` on 2021-01-20`

**Comment by SuperQ** [comment]
We're seeing a similar issue. We noticed some indexes that in bytes don't go over 64GiB, but when the indexes are merged they bloat to larger than 64GiB.  See: https://github.com/thanos-io/thanos/issues/3724

We have been manually marking them with the bucke tool, but it seems to be not reading this marker file consistently. I've deployed a patched version with some debug logging to see if we can catch the problem.

Our internal issue: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/3427

**Comment by SuperQ** [comment]
We have a couple of blocks that refuse to avoid compaction:
```
{
  "caller": "markers.go:103",
  "filename": "01EJQ1JVX2RYAVAVBC1CJCESJD/no-compact-mark.json",
  "level": "debug",
  "msg": "Reading marker file",
  "ts": "2021-01-29T01:28:13.043493391Z"
}
{
  "caller": "markers.go:103",
  "filename": "01EWEZY495D167Q9SRKBAXM6KJ/no-compact-mark.json",
  "level": "debug",
  "msg": "Reading marker file",
  "ts": "2021-01-29T01:29:12.554334665Z"
}
{
  "caller": "compact.go:426",
  "err": "compaction: group 300000@4648145191823988568: compact blocks [/opt/prometheus/thanos/compact-data/compact/300000@4648145191823988568/01EJQ1JVX2RYAVAVBC1CJCESJD /opt/prometheus/thanos/compact-data/compact/300000@4648145191823988568/01EWEZY495D167Q9SRKBAXM6KJ]: \"/opt/prometheus/thanos/compact-data/compact/300000@4648145191823988568/01EX52DDPDTDE02DC6FBYR6RCY.tmp-for-creation/index\" exceeding max size of 64GiB",
  "level": "error",
  "msg": "critical error detected; halting",
  "ts": "2021-01-29T01:30:29.408758792Z"
}
```

**Comment by kakkoyun** [comment]
Hey @SuperQ, is #3773 a fix or a stopgap for this issue? Thanks for the PR btw.
@rbounds Have you tested it?

**Comment by rbounds** [comment]
@kakkoyun No, I've not tested this. It appears that #3773 fixes really addresses #3724 and this issue is still outstanding.

**Comment by SuperQ** [comment]
@kakkoyun It's needed in addition to a fix for why the `no-compact-mark.json` file is being igored.

**Comment by Lord-Y** [comment]
Hello guys,

Were having the same issue with thanos version 0.18.0 but this time, the blocks are way bigger:

```
level=error ts=2021-03-10T01:40:14.642943923Z caller=compact.go:426 msg="critical error detected; halting" err="compaction: group 0@18221892084446967409: compact blocks [/data/thanos/compactor/compact/0@18221892084446967409/01EWWWVR3PBKXZ5XAY42KD4Z76 /data/thanos/compactor/compact/0@18221892084446967409/01EWX3HYN3CW0NRC7Y9RRMW67H /data/thanos/compactor/compact/0@18221892084446967409/01EX5A87DX9FDBDPC06WJ034TV /data/thanos/compactor/compact/0@18221892084446967409/01EX67P4TJE8FE8PF6ERHEXK3A /data/thanos/compactor/compact/0@18221892084446967409/01EXF6H67ABRDAF0877V11YKRF /data/thanos/compactor/compact/0@18221892084446967409/01EXGFC56J6ETJE63443V9DEG8 /data/thanos/compactor/compact/0@18221892084446967409/01EXS7JB4HVYECZ8R32ZTV75MJ]: \"/data/thanos/compactor/compact/0@18221892084446967409/01F0C9F7T07YRBRN3KCJCJJRE7.tmp-for-creation/index\" exceeding max size of 64GiB"

27.8 GiB     gs://XXXX/01EWWWVR3PBKXZ5XAY42KD4Z76
30.48 GiB    gs://XXXX/01EWX3HYN3CW0NRC7Y9RRMW67H
31.27 GiB    gs://XXXX/01EX5A87DX9FDBDPC06WJ034TV
29.62 GiB    gs://XXXX/01EX67P4TJE8FE8PF6ERHEXK3A
30.37 GiB    gs://XXXX/01EXF6H67ABRDAF0877V11YKRF
31.5 GiB     gs://XXXX/01EXGFC56J6ETJE63443V9DEG8
32.05 GiB    gs://XXXX/01EXS7JB4HVYECZ8R32ZTV75MJ
213.09 GiB   total
```

Exact thanos version:
```
thanos, version 0.18.0 (branch: HEAD, revision: 60d45a02d46858a38013283b578017a171cf7b82)
  build user:       root@4cf3f59273a2
  build date:       20210127-12:18:59
  go version:       go1.15.7
  platform:         linux/amd64
```

Any plan to release a fix soon with also the one about `no-compact-mark.json file is being igored` as mentioned by @SuperQ

**Comment by Lord-Y** [comment]
@kakkoyun @bwplotka do you guys have a chance to look at this issue?

**Comment by Biswajitghosh98** [comment]
I'm working on this issue and we have an ongoing progress, and this is expected to be fixed soon :)

**Comment by rbounds** [comment]
Yes still remains a problem .

**Comment by gkope** [comment]
Same problem here

```
level=error ts=2021-07-23T06:37:34.132595178Z caller=compact.go:426 msg="critical error detected; halting" err="compaction: group 0@3574896491107694491: compact blocks [/data/compact/0@3574896491107694491/01FACF62KXZ7VY165EKX00V31B /data/compact/0@3574896491107694491/01FAHN78FTRHZM4JWQGA37STXZ /data/compact/0@3574896491107694491/01FAPSN40GENT45CSKF64MZJZZ /data/compact/0@3574896491107694491/01FAVX9AMGPAB6X2TB4JSZYFTY /data/compact/0@3574896491107694491/01FB128YJ9QFQ4PPQ0TXSA1209 /data/compact/0@3574896491107694491/01FB67KKTK3TYZY5W9G0R0DS1A]: \"/data/compact/0@3574896491107694491/01FB85WABXP60268RWATM25QVV.tmp-for-creation/index\" exceeding max size of 64GiB"
```

**Comment by rbounds** [comment]
Still an issue. @bwplotka in #3773 you said this was on your todo list. Has this been addressed yet?

**Comment by rbounds** [comment]
Still needed

**Comment by yeya24** [comment]
@rbounds Is this still happening on latest v0.24.0?

**Comment by rbounds** [comment]
> @rbounds Is this still happening on latest v0.24.0?

@yeya24 Is there a reason I should expect it not to? Doesn't seem to be anything in the change log that looks indicative of a fix here.

**Comment by jimethn** [comment]
Still a problem.
