### ISSUE TITLE
Component Receiver forward requests to faulty node where the node configurated in hashrings file

### ISSUE THREAD

**Issue by yutian-github** [thanos-io/thanos#4059]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:
I have two receiver nodes, and a loadbalance is deployed in front of the receiver nodes, when a receiver node is faulty, another healthy node still forwards requests to the faulty node. All nodes are configured in the hashings file. In this case, grafana does not seem to be able to query the data from receiver nodes.
**What you expected to happen**:
When a receiver node is faulty, the healthy node should not forward requests to the faulty node. Or whether hashings is not used for forwarding?
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by wiardvanrij** [comment]
Hi, as you describe this, it seems like a fair point. Though I think this needs more investigation on wether this is actually the case or not. 

Could you perhaps provide an example case on how one could reproduce this exactly?

**Comment by yutian-github** [comment]
> Hi, as you describe this, it seems like a fair point. Though I think this needs more investigation on wether this is actually the case or not.
> 
> Could you perhaps provide an example case on how one could reproduce this exactly?

For example:
I have two receiver nodes, one with an IP address of 172.168.0.1 and the other with an IP address of 172.168.0.2, and a loadbalance is deployed in front of the two receiver nodes to receiver metrics from prometheus.

The command parameters of 172.168.0.1 is:
--tsdb.path="/data"
--tsdb.retention="2h"
--grpc-address="172.168.0.1:10907"
--grpc-server-tls-cert="/etc/receiver/server.pem"
--grpc-server-tls-key="/etc/receiver/server.key"
--grpc-server-tls-client-ca="/etc/receiver/ca.cer"
--http-address="172.168.0.1:10909"
--remote-write.server-tls-cert="/etc/receiver/server.pem"
--remote-write.server-tls-key="/etc/receiver/server.key"
--remote-write.server-tls-client-ca="/etc/receiver/ca.cer"
--remote-write.client-tls-cert="/etc/receiver/client.pem"
--remote-write.client-tls-key="/etc/receiver/client.key"
--remote-write.client-tls-ca="/etc/receiver/ca.cer"
--receive.replication-factor="1"
--label="receive_replica="172.168.0.1""
--receive.local-endpoint="172.168.0.1:10907"
--receive.hashrings-file="/etc/receiver/hashring.json"
--remote-write.address="172.168.0.1:10908""
--objstore.config-file="/etc/receiver/bucket.yml""
And the hashring.json file content of 172.168.0.1 is:
 [
    {
        "endpoints": [
            "172.168.0.1:10907",
            "172.168.0.2:10907",
        ]
    }
]

The command parameters of 172.168.0.2 is:
--tsdb.path="/data"
--tsdb.retention="2h"
--grpc-address="172.168.0.2:10907"
--grpc-server-tls-cert="/etc/receiver/server.pem"
--grpc-server-tls-key="/etc/receiver/server.key"
--grpc-server-tls-client-ca="/etc/receiver/ca.cer"
--http-address="172.168.0.2:10909"
--remote-write.server-tls-cert="/etc/receiver/server.pem"
--remote-write.server-tls-key="/etc/receiver/server.key"
--remote-write.server-tls-client-ca="/etc/receiver/ca.cer"
--remote-write.client-tls-cert="/etc/receiver/client.pem"
--remote-write.client-tls-key="/etc/receiver/client.key"
--remote-write.client-tls-ca="/etc/receiver/ca.cer"
--receive.replication-factor="1"
--label="receive_replica="172.168.0.2""
--receive.local-endpoint="172.168.0.2:10907"
--receive.hashrings-file="/etc/receiver/hashring.json"
--remote-write.address="172.168.0.2:10908""
--objstore.config-file="/etc/receiver/bucket.yml""
And the hashring.json file content of 172.168.0.2 is:
 [
    {
        "endpoints": [
            "172.168.0.1:10907",
            "172.168.0.2:10907",
        ]
    }
]

When both nodes are running properly, the grafana view is displayed properly. When I kill a node's process, for example 172.168.0.1, another node 172.168.0.2 has the error log: 
level=error ts=2021-04-14T09:42:27.195984409Z caller=handler.go:331 component=receive component=receive-handler err="backing off forward request for endpoint 172.168.0.1:10907: target not available" msg="internal server error"
In this case, grafana cannot display the lastest real-time data. When I start the receiver process on the node 172.168.0.1, the grafana is back to normal.

**Comment by wiardvanrij** [comment]
I assume you are running the Query component with each receivers added as store? Not via a LB? Then I also assume you have configured Grafana to Thanos Query?

**Comment by yutian-github** [comment]
> I assume you are running the Query component with each receivers added as store? Not via a LB? Then I also assume you have configured Grafana to Thanos Query?

Yeh, you are right. I added all the two receiver nodes as store in query component, and configurated the quey component endpoint as grafana datasource.

**Comment by wiardvanrij** [comment]
Ok, so the summery is: 

- Run x2 receive 
- Have Query component with those 2 receive endpoints
- Kill one receive
- -> Results in no queryable data, even though one receive endpoint is still up and available. 

I think we could define this as a bug which should be resolved. 
Open for more investigation if this is reproducible and/or intended (?)

**Comment by kakkoyun** [comment]
@yutian-github What is the expected behaviour here? 
As far as I understood, the receive nodes behave as they designed to be. You give an hashring configuration with 2 nodes and you have a replication factor of 1. So the expected behaviour is the receiver to fail in this case. In this configuration, you are sharding incoming traffic between, two given nodes as a result the nodes have to be there.

If you want something dynamic you should use something like https://github.com/observatorium/thanos-receive-controller to dynamically scale up or down the hashring.

If you want to tolerate partial failures in the hashring you need to enable replication.

**Comment by wiardvanrij** [comment]
> > You give an hashring configuration with 2 nodes and you have a replication factor of 1. So the expected behaviour is the receiver to fail in this case.

The replication factor of 1 requires a quorum of 1. Unless I'm mistaken here in the logic of this

**Comment by yutian-github** [comment]
> > > You give an hashring configuration with 2 nodes and you have a replication factor of 1. So the expected behaviour is the receiver to fail in this case.
> 
> The replication factor of 1 requires a quorum of 1. Unless I'm mistaken here in the logic of this

When I have the replication factor of 2, killed one receiver node, the grafana still fails to query the latest data. So this is normal, not a problem?

**Comment by yutian-github** [comment]
> @yutian-github What is the expected behaviour here?
> As far as I understood, the receive nodes behave as they designed to be. You give an hashring configuration with 2 nodes and you have a replication factor of 1. So the expected behaviour is the receiver to fail in this case. In this configuration, you are sharding incoming traffic between, two given nodes as a result the nodes have to be there.
> 
> If you want something dynamic you should use something like https://github.com/observatorium/thanos-receive-controller to dynamically scale up or down the hashring.
> 
> If you want to tolerate partial failures in the hashring you need to enable replication.

When I have the replication factor of 2, killed one receiver node, the grafana still fails to query the latest data. So this is normal, not a problem?
